name: Builder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  builder:
    runs-on: ubuntu-20.04
    steps:
    - name: Check Out Code
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install deps
      run: npm install
    - name: Run app
      run: nohup npm run start &
    - name: Run HawkScan
      uses: stackhawk/hawkscan-action@v1.2.1
      with:
        apiKey: ${{ secrets.HAWK_API_KEY }}
      
